In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x .fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
#create age columns

labels = ['Young adult','Adult','Middle aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels = labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle aged
1   19  Young adult
2   50  Middle aged
3   21  Young adult
4   45  Middle aged
5   46  Middle aged
6   63       Senior
7   27  Young adult
8   26  Young adult
9   57  Middle aged

In [14]:
#create columns purchase_frequency_days
fequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Bi-weekly' : 14,
    'Annually' : 365,
    'Every 3 month' : 90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(fequency_mapping)

In [15]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [16]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [17]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [18]:
df = df.drop('promo_code_used',axis = 1 )

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [20]:
!pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\asus\appdata\roaming\python\python313\site-packages (1.2.0)

In [21]:
!pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\asus\appdata\roaming\python\python313\site-packages (1.2.0)

In [22]:
!conda install -y -c anaconda pymysql

Jupyter detected...
3 channel Terms of Service accepted
Retrieving notices: done

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: G:\Anconda

In [23]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Using cached mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Using cached mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [24]:
import pandas as pd
from sqlalchemy import create_engine

# Using a distinct driver structure that bypasses special character string limitations
engine = create_engine(
    "mysql+mysqlconnector://root:Asdfg&12345@localhost:3306/sys"
)

# Test the connection by pulling your workbench data
query = "SELECT * FROM sys_config"
df = pd.read_sql(query, con=engine)
df.head()

                               variable  value            set_time set_by
0          diagnostics.allow_i_s_tables    OFF 2026-07-02 10:39:16   None
1               diagnostics.include_raw    OFF 2026-07-02 10:39:16   None
2         ps_thread_trx_info.max_length  65535 2026-07-02 10:39:16   None
3  statement_performance_analyzer.limit    100 2026-07-02 10:39:16   None
4   statement_performance_analyzer.view   None 2026-07-02 10:39:16   None

In [27]:
df.head(10)

                               variable  value            set_time set_by
0          diagnostics.allow_i_s_tables    OFF 2026-07-02 10:39:16   None
1               diagnostics.include_raw    OFF 2026-07-02 10:39:16   None
2         ps_thread_trx_info.max_length  65535 2026-07-02 10:39:16   None
3  statement_performance_analyzer.limit    100 2026-07-02 10:39:16   None
4   statement_performance_analyzer.view   None 2026-07-02 10:39:16   None
5                statement_truncate_len     64 2026-07-02 10:39:16   None

In [29]:
# Change 'your_new_table' to the actual table 'sys_config'
query = "SELECT * FROM sys_config"
new_df = pd.read_sql(query, con=engine)
new_df.head()

                               variable  value            set_time set_by
0          diagnostics.allow_i_s_tables    OFF 2026-07-02 10:39:16   None
1               diagnostics.include_raw    OFF 2026-07-02 10:39:16   None
2         ps_thread_trx_info.max_length  65535 2026-07-02 10:39:16   None
3  statement_performance_analyzer.limit    100 2026-07-02 10:39:16   None
4   statement_performance_analyzer.view   None 2026-07-02 10:39:16   None

In [30]:
import pandas as pd
from sqlalchemy import create_engine

# ১. আপনার MySQL কানেকশন ইঞ্জিন তৈরি করুন (যা আগেরবার সাকসেসফুলি কাজ করেছিল)
engine = create_engine(
    "mysql+mysqlconnector://root:Asdfg&12345@localhost:3306/sys"
)

# ২. আপনি টেবিলের কী নাম দিতে চান তা এখানে লিখুন
table_name = "customer_behavior_table"

# ৩. এই লাইনের মাধ্যমে আপনার df-এর পুরো ডাটা MySQL-এর 'sys' ডাটাবেজে আপলোড হয়ে যাবে
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into MySQL table '{table_name}' inside 'sys' database.")

Data successfully loaded into MySQL table 'customer_behavior_table' inside 'sys' database.

In [31]:
pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5", con=engine)

                               variable  value            set_time set_by
0          diagnostics.allow_i_s_tables    OFF 2026-07-02 10:39:16   None
1               diagnostics.include_raw    OFF 2026-07-02 10:39:16   None
2         ps_thread_trx_info.max_length  65535 2026-07-02 10:39:16   None
3  statement_performance_analyzer.limit    100 2026-07-02 10:39:16   None
4   statement_performance_analyzer.view   None 2026-07-02 10:39:16   None

In [3]:
import pandas as pd
from sqlalchemy import create_engine

# এই সেলটি রান করে কানেকশনটি আবার সচল করে নিন
engine = create_engine(
    "mysql+mysqlconnector://root:Asdfg&12345@localhost:3306/sys"
)

In [4]:
# ডাটাবেজ থেকে ডাটা লোড করে দেখা
df = pd.read_sql("SELECT * FROM customer_behavior_table", con=engine)
df.head()

                               variable  value            set_time set_by
0          diagnostics.allow_i_s_tables    OFF 2026-07-02 10:39:16   None
1               diagnostics.include_raw    OFF 2026-07-02 10:39:16   None
2         ps_thread_trx_info.max_length  65535 2026-07-02 10:39:16   None
3  statement_performance_analyzer.limit    100 2026-07-02 10:39:16   None
4   statement_performance_analyzer.view   None 2026-07-02 10:39:16   None

In [8]:


# quotes এর ভেতরে আপনার কপি করা পাথটি পেস্ট করুন। সামনে 'r' দিতে ভুলবেন না।
df_customer = pd.read_csv("customer_shopping_behavior.csv")

# ডাটা চেক করার জন্য
df_customer.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
# কাস্টমার ডাটা ফ্রেমটিকে MySQL ডাটাবেজে 'customer_table' নামে সেভ করছি
df_customer.to_sql("customer_shopping_behavior.csv", con=engine, if_exists="replace", index=False)

print("কাস্টমার ডাটা সফলভাবে MySQL-এ আপলোড হয়েছে!")

কাস্টমার ডাটা সফলভাবে MySQL-এ আপলোড হয়েছে!

# 'customer_table' এর জায়গায় সঠিক নাম 'customer_behavior_table' ব্যবহার করুন
df_final = pd.read_sql("SELECT * FROM customer_behavior_table LIMIT 5", con=engine)
df_final.head()

In [13]:
# আপনার MySQL টেবিল থেকে প্রথম ২০টি ডাটা দেখা
query = "SELECT * FROM customer_behavior_table LIMIT 20;"

df_result = pd.read_sql(query, con=engine)
df_result

                               variable  value            set_time set_by
0          diagnostics.allow_i_s_tables    OFF 2026-07-02 10:39:16   None
1               diagnostics.include_raw    OFF 2026-07-02 10:39:16   None
2         ps_thread_trx_info.max_length  65535 2026-07-02 10:39:16   None
3  statement_performance_analyzer.limit    100 2026-07-02 10:39:16   None
4   statement_performance_analyzer.view   None 2026-07-02 10:39:16   None
5                statement_truncate_len     64 2026-07-02 10:39:16   None

In [14]:
# ১. প্রথমে আপনার পিসির ফোল্ডারে থাকা আসল কাস্টমার ডাটা ফাইলটি পাইথনে লোড করুন
# (এখানে আপনার ফাইলের আসল পাথটি বসিয়ে দিন)
df_customer = pd.read_csv(
    "customer_shopping_behavior.csv"
)

# ২. এবার এই আসল ডাটা দিয়ে MySQL এর টেবিলটিকে রিপ্লেস (সঠিকভাবে আপলোড) করে দিন
df_customer.to_sql(
    "customer_behavior_table", con=engine, if_exists="replace", index=False
)

print("খেলা শেষ! আসল কাস্টমার ডাটা এখন MySQL-এ সাকসেসফুলি আপলোড হয়ে গেছে।")

খেলা শেষ! আসল কাস্টমার ডাটা এখন MySQL-এ সাকসেসফুলি আপলোড হয়ে গেছে।